# Generated by Django 4.1.5 on 2023-03-20 01:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Items",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=50, unique=True)),
                ("description", models.TextField(max_length=500)),
                ("price", models.IntegerField()),
                ("quantity", models.IntegerField()),
                (
                    "date_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
