# Generated by Django 4.1.5 on 2023-03-20 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Items",
            new_name="Orders",
        ),
    ]
