# Generated by Django 4.1.5 on 2023-03-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_delete_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="favorites",
            field=models.BooleanField(default=False),
        ),
    ]
