# Generated by Django 4.1.5 on 2023-03-24 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0006_orders_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orders",
            options={"ordering": ["-date_updated"]},
        ),
    ]
